// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hsfujyzgvwmcrxzzzoof.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhzZnVqeXpndndtY3J4enp6b29mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5NDA4ODYsImV4cCI6MjA2OTUxNjg4Nn0.GUyvkLLwEasVjzsHjOZmnCcKP4FFemUQ-E-l66Zeva8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});